### ISSUE TITLE
Homebridge will not show in iOS app

### ISSUE THREAD

**Issue by marcelveldt** [hassio-addons/repository#5] opened 2017-08-15 10:16 UTC
## Problem/Motivation

Homebridge won't show up in the Home app on my iOS device.
I've also checked with Bonjour Browser from my Mac and I don't see any references there to Homebridge.

## Expected behavior

Homebridge/Homeassistant should show up in my Home app on iOS as accessory so I can connect with the PIN and have it discovering my devices.

## Actual behavior

Homebridge doesn't show up at all.
I do notice some related error in the log:
Host name conflict, retrying with hassio-15

It should be noted that I changed the default hassio hostname to "home assistant" instead of "hassio".

## Steps to reproduce

Not sure, just followed the default configuration steps.

## Proposed changes

I did not yet test it, but I suppose it's related to the hostname change.

Full log attached
[homebridge_log.txt](https://github.com/hassio-addons/repository/files/1224769/homebridge_log.txt)

**Comment by frenck** [comment] 2017-08-15 10:18
@marcelveldt Thank for submitting this issue.
It might be related to #2.

I will check this as soon as I can.

**Comment by marcelveldt** [comment] 2017-08-15 10:20
Thanks for the prompt reply. Forgot to mention I'm running HassIO on a raspberry pi 3. Just a default install with only difference is that I changed the hostname and I'm running home assistant on SSL/HTTPS

**Comment by steeve** [comment] 2017-08-17 00:10
Hey folks,

I have the same problem and narrowed it down to avahi being unable to get past the "register" phase:

```
root@hassio:~# docker exec -it 9556aadd7bd0 ps
PID   USER     TIME   COMMAND
    1 root       0:00 bash /run.sh
    9 root       0:00 udevd
   18 messageb   0:00 dbus-daemon --system
   19 root       0:00 bash /run.sh
   21 avahi      0:00 avahi-daemon: registering [hassio.local]
   22 avahi      0:00 avahi-daemon: chroot helper
   25 root       0:03 homebridge
  100 root       0:00 ps
```

I managed to make it change to `running` when I run the container myself, although not on this image.

**Comment by steeve** [comment] 2017-08-17 00:14
Also, not sure if it helped but I changed the `avahi-daemon.conf` to only bind on real interfaces (since it is running host anyway) via
```
allow-interfaces=eth0,wlan0
```

I was able to get avahi to register, but only when manually started, not via HA.

**Comment by steeve** [comment] 2017-08-17 00:30
Yes, confirmed, when I add these lines to your image, it registers properly and I can see in the Home app

**Comment by marcelveldt** [comment] 2017-08-17 07:54
In my case, I had to change the line host-name in the avahi-daemon.conf to match my hostname and it was working.

**Comment by frenck** [comment] 2017-08-17 08:12
@steeve & @marcelveldt 

Thank you guys for debugging and finding solutions.

A possible path of resolving this issue is:

*Adding configuration option `avahi-interfaces`*:

Which will be defaulted to something sensible, but can be overridden by the user.
A sensible default could be `eth0,wlan0`, since that would work for 99% of the Hass.io users. 
I could also actually pick up the physical interfaces used by docker and use those. Using this command might work:

```bash
$ ls -l /sys/class/net/ | grep '/devices/platform' | awk '{print $9}'
eth0
wlan0
```

*Adding configuration option `avahi-hostname`*:

Which will be defaulted to something sensible, but can be overridden by the user.
A sensible default could be `hassio`, since that would work for 99% of the Hass.io users.
Another option is to query the hassio API. Using this command might work:

```bash
$ curl -s -X GET "http://hassio/host/info" | jq --raw-output ".data.hostname"
hassio
```

Does this sound like a sensible solution to you guys?

**Comment by marcelveldt** [comment] 2017-08-17 08:14
fantastic!

**Comment by steeve** [comment] 2017-08-17 09:38
That indeed sounds awesome @frenck

**Comment by nic0dk** [comment] 2017-08-19 22:03
somehow i cant get the avahi service stop on the docker host.
what command do you guys used ?

**Comment by frenck** [comment] 2017-08-21 18:10
I moved this issue to the new dedicated GitHub repository for the Homebridge addon.

For further development of this issue, please see hassio-addons/addon-homebridge#3

**Closed by frenck** 2017-08-21 18:10 UTC
Labels: Add-on: Homebridge, enhancement
