### ISSUE TITLE
Feature request: EmonCMS

### ISSUE THREAD

**Issue by RikVerstijnen** [hassio-addons/repository#152] opened 2019-05-13 12:11 UTC
[EmonCMS ](https://www.home-assistant.io/components/emoncms_history/)is a great platform to process and visualize timeseries data. They offer a cloud-hosted environment, but have recently announced that they will start charging £1/feed/year for the cloud-hosted stuff. This will raise the need to arrange a self-hosted environment.

An [EmonCMS docker](https://github.com/emoncms/emoncms-docker) already exists. Is anyone willing to create a Hassio add-on for EmonCMS? This will be greatly appreciated.

**Comment by frenck** [comment] 2019-05-13 13:07
Duplicate of #92

**Closed by frenck** 2019-05-13 13:07 UTC
