### ISSUE TITLE
VPN Server with piVPN

### ISSUE THREAD

**Issue by beloso** [hassio-addons/repository#85] opened 2018-08-24 15:51 UTC
It would be nice to create a PiVPN as an add on for HASSIO

http://www.pivpn.io

<blockquote><div><strong><a href="http://www.pivpn.io/">PiVPN: Simplest setup of OpenVPN</a></strong></div></blockquote>

**Comment by tjorim** [comment] 2018-08-24 18:45
Duplicate of #18, PiVPN is just a wrapper for OpenVPN.

**Closed** 2018-08-31 19:16 UTC
