### ISSUE TITLE
Possible mDNS conflict?

### ISSUE THREAD

**Issue by mihalski** [hassio-addons/repository#2] opened 2017-08-14 21:27 UTC
I am witnessing the below behaviour on a generic linux hassio install:
```
starting version 3.2.2
[ADD-ON] Ensuring old PID files are absent
[ADD-ON] Ensuring D-Bus unique ID exists
[ADD-ON] Starting D-Bus daemon
[ADD-ON] [DEBUG] Waiting until system bus socket is ready
[ADD-ON] Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
chroot.c: chroot() helper started
chroot.c: chroot() helper got command 02
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface ens18.IPv4 with address 192.168.1.123.
New relevant interface ens18.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::4ca2:f6ff:fe09:c85b on veth447c64d.*.
Registering new address record for fe80::5c7c:eff:fe43:b783 on veth5a80865.*.
Registering new address record for fe80::2413:43ff:febc:6c03 on vethd1224a2.*.
Registering new address record for fe80::4c47:79ff:fec2:7594 on veth57cec18.*.
Registering new address record for fe80::d808:39ff:fe6d:b197 on vethcc0d4cf.*.
Registering new address record for fe80::dcc9:97ff:fe55:ccce on veth2d3dc9d.*.
Registering new address record for fe80::8a2:94ff:fe1b:9ab1 on veth4f260ca.*.
Registering new address record for fe80::9872:60ff:fe8e:bd20 on veth167dcb8.*.
Registering new address record for fe80::8850:e6ff:fe43:495f on veth67218b8.*.
Registering new address record for fe80::72:beff:fe75:e4d on veth7b8aa8e.*.
Registering new address record for fe80::dc4b:dfff:fef0:f17d on veth57c298b.*.
Registering new address record for fe80::42:b3ff:fe32:b559 on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::5c9b:2ff:fe44:e075 on ens18.*.
Registering new address record for 192.168.1.123 on ens18.IPv4.
Server startup complete. Host name is hassio.local. Local service cookie is 74177856.
Received conflicting record [hassio.local	IN	AAAA fe80::f57b:e107:3e18:9922 ; ttl=120] with local record to be. Withdrawing.
Withdrawing address record for fe80::4ca2:f6ff:fe09:c85b on veth447c64d.
Withdrawing address record for fe80::5c7c:eff:fe43:b783 on veth5a80865.
Withdrawing address record for fe80::2413:43ff:febc:6c03 on vethd1224a2.
Withdrawing address record for fe80::4c47:79ff:fec2:7594 on veth57cec18.
Withdrawing address record for fe80::d808:39ff:fe6d:b197 on vethcc0d4cf.
Withdrawing address record for fe80::dcc9:97ff:fe55:ccce on veth2d3dc9d.
Withdrawing address record for fe80::8a2:94ff:fe1b:9ab1 on veth4f260ca.
Withdrawing address record for fe80::9872:60ff:fe8e:bd20 on veth167dcb8.
Withdrawing address record for fe80::8850:e6ff:fe43:495f on veth67218b8.
Withdrawing address record for fe80::72:beff:fe75:e4d on veth7b8aa8e.
Withdrawing address record for fe80::dc4b:dfff:fef0:f17d on veth57c298b.
Withdrawing address record for fe80::42:b3ff:fe32:b559 on docker0.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for 192.168.1.123 on ens18.
Host name conflict, retrying with hassio-2
```
It just keeps going and incrementing the host name.
It may be relevant that the docker host itself is running mDNS on 192.168.1.123 (for the purposes of mosquitto container auto discovery as that's not built into the add-on).

**Comment by frenck** [comment] 2017-08-14 21:35
Thank you for submitting an issue. This add-on is not tested on a generic Linux Hass.io installation, but it "should" not be a problem. Nevertheless, you have a valid issue on your hands.

Could you be so kind and try stopping the mDNS on the docker host, just for the sake of checking if this is actually causing the issue?

**Comment by mihalski** [comment] 2017-08-14 21:44
Interesting.. If I disable avahi-daemon on the host it settles on hassio-2 and then continues on to start. Mind you the Home app refuses to accept the pin it generated. I've deleted the entire home bridge folder and restarted so that it would generate a new code but that didn't help. Nothing in the logs about the Home app trying to connect (even with debug on).
```
starting version 3.2.2
[ADD-ON] Ensuring old PID files are absent
[ADD-ON] Ensuring D-Bus unique ID exists
[ADD-ON] Starting D-Bus daemon
[ADD-ON] [DEBUG] Waiting until system bus socket is ready
[ADD-ON] Starting Avahi daemon
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.6.32 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
chroot.c: chroot() helper startedSuccessfully called chroot().
Successfully dropped remaining capabilities.

chroot.c: chroot() helper got command 02
Loading service file /services/sftp-ssh.service.
Loading service file /services/ssh.service.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.0.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface ens18.IPv4 with address 192.168.1.123.
New relevant interface ens18.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::4ca2:f6ff:fe09:c85b on veth447c64d.*.
Registering new address record for fe80::5c7c:eff:fe43:b783 on veth5a80865.*.
Registering new address record for fe80::2413:43ff:febc:6c03 on vethd1224a2.*.
Registering new address record for fe80::4c47:79ff:fec2:7594 on veth57cec18.*.
Registering new address record for fe80::d808:39ff:fe6d:b197 on vethcc0d4cf.*.
Registering new address record for fe80::dcc9:97ff:fe55:ccce on veth2d3dc9d.*.
Registering new address record for fe80::8a2:94ff:fe1b:9ab1 on veth4f260ca.*.
Registering new address record for fe80::9872:60ff:fe8e:bd20 on veth167dcb8.*.
Registering new address record for fe80::8850:e6ff:fe43:495f on veth67218b8.*.
Registering new address record for fe80::72:beff:fe75:e4d on veth7b8aa8e.*.
Registering new address record for fe80::dc4b:dfff:fef0:f17d on veth57c298b.*.
Registering new address record for fe80::42:b3ff:fe32:b559 on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::5c9b:2ff:fe44:e075 on ens18.*.
Registering new address record for 192.168.1.123 on ens18.IPv4.
Server startup complete. Host name is hassio.local. Local service cookie is 2746813551.
Received conflicting record [hassio.local	IN	AAAA fe80::f57b:e107:3e18:9922 ; ttl=120] with local record to be. Withdrawing.
Withdrawing address record for fe80::4ca2:f6ff:fe09:c85b on veth447c64d.
Withdrawing address record for fe80::5c7c:eff:fe43:b783 on veth5a80865.
Withdrawing address record for fe80::2413:43ff:febc:6c03 on vethd1224a2.
Withdrawing address record for fe80::4c47:79ff:fec2:7594 on veth57cec18.
Withdrawing address record for fe80::d808:39ff:fe6d:b197 on vethcc0d4cf.
Withdrawing address record for fe80::dcc9:97ff:fe55:ccce on veth2d3dc9d.
Withdrawing address record for fe80::8a2:94ff:fe1b:9ab1 on veth4f260ca.
Withdrawing address record for fe80::9872:60ff:fe8e:bd20 on veth167dcb8.
Withdrawing address record for fe80::8850:e6ff:fe43:495f on veth67218b8.
Withdrawing address record for fe80::72:beff:fe75:e4d on veth7b8aa8e.
Withdrawing address record for fe80::dc4b:dfff:fef0:f17d on veth57c298b.
Withdrawing address record for fe80::42:b3ff:fe32:b559 on docker0.
Withdrawing address record for 172.17.0.1 on docker0.
Withdrawing address record for 192.168.1.123 on ens18.
Host name conflict, retrying with hassio-2
Registering new address record for fe80::4ca2:f6ff:fe09:c85b on veth447c64d.*.
Registering new address record for fe80::5c7c:eff:fe43:b783 on veth5a80865.*.
Registering new address record for fe80::2413:43ff:febc:6c03 on vethd1224a2.*.
Registering new address record for fe80::4c47:79ff:fec2:7594 on veth57cec18.*.
Registering new address record for fe80::d808:39ff:fe6d:b197 on vethcc0d4cf.*.
Registering new address record for fe80::dcc9:97ff:fe55:ccce on veth2d3dc9d.*.
Registering new address record for fe80::8a2:94ff:fe1b:9ab1 on veth4f260ca.*.
Registering new address record for fe80::9872:60ff:fe8e:bd20 on veth167dcb8.*.
Registering new address record for fe80::8850:e6ff:fe43:495f on veth67218b8.*.
Registering new address record for fe80::72:beff:fe75:e4d on veth7b8aa8e.*.
Registering new address record for fe80::dc4b:dfff:fef0:f17d on veth57c298b.*.
Registering new address record for fe80::42:b3ff:fe32:b559 on docker0.*.
Registering new address record for 172.17.0.1 on docker0.IPv4.
Registering new address record for fe80::5c9b:2ff:fe44:e075 on ens18.*.
Registering new address record for 192.168.1.123 on ens18.IPv4.
Server startup complete. Host name is hassio-2.local. Local service cookie is 2746813551.
Service "hassio-2" (/services/ssh.service) successfully established.
Service "hassio-2" (/services/sftp-ssh.service) successfully established.
[ADD-ON] Applying HAP NodeJS IPV6 HOTFIX
patching file /usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/util/eventedhttp.js
[ADD-ON] Starting Homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
```

**Comment by mihalski** [comment] 2017-08-14 21:46
BTW, I noticed the pins are always generated as 290--22-311 (with the double dash.. Is this s bug?

**Comment by frenck** [comment] 2017-08-14 21:47
That last one looks like a bug, could you please create a separate issue for this?

**Comment by fosty148** [comment] 2017-08-18 19:25
Getting something similar.

[ADD-ON] Applying HAP NodeJS IPV6 HOTFIX
patching file /usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/util/eventedhttp.js
[ADD-ON] Starting Homebridge
module.js:472
    throw err;
    ^
Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by frenck** [comment] 2017-08-18 19:43
@fosty148 Thank you for the report, but unfortunately, that is not similar. 
The bug you are reporting is a duplicate of issue #6.

**Comment by fosty148** [comment] 2017-08-18 19:53
@frenck  many thanks.  is it fixable?

**Comment by frenck** [comment] 2017-08-18 19:56
@fosty148 Yes it is.
If you have any further questions, or in the need to discuss the technical details further, I would kindly ask you to continue in #6, so this issue can be kept on topic.

**Comment by frenck** [comment] 2017-08-21 18:13
I've moved this issue to the dedicated GitHub repository of the Homebridge addon.

For more information and the tracking of the progress of this issue, please see:
hassio-addons/addon-homebridge#3

**Closed by frenck** 2017-08-21 18:13 UTC
Labels: Add-on: Homebridge, help wanted
