### ISSUE TITLE
The zwave-js-ui upgrade is nondeterministic, due to the zwavejs2mqtt folder remaining in place.

### ISSUE THREAD

**Issue by KevinCathcart** [hassio-addons/repository#439] opened 2022-09-25 20:38 UTC
# Problem/Motivation

The presence of both `zwave-js-ui/config.yaml` and `zwavejs2mqtt/config.yaml` (which both specify the same slug) means that intended seemless upgrade experience does not work for all users. This comes down to non-determinism in file iteration order in linux, which is exposed by python. See home-assistant/supervisor#3894 for the details.

## Expected behavior

Home assistant offers to upgrade the old zwavejs2mqtt plugin to the new Z-Wave JS UI plugin seemlessly.

## Actual behavior

The newer name of the plugin does not appear at all, and no update is offered.

## Steps to reproduce

This is sadly nondeterministic, so it is non-trivial to reproduce. Specifically it depends on the exact order that the filesystem returns the directories in the repository, which can vary depending on the filesystem used, the order in which directories are written, etc.

## Proposed changes

Remove the zwavejs2mqtt subfolder. By removing it there will only be one subfolder that specifies the `zwavejs2mqtt` slug, which will ensure that the newest one is always used by the supervisor, resulting in the update being available for all users regardless of iteration order.

This same issue also affects the beta repository, and probably also the edge repository.

**Comment by ImSorryButWho** [comment] 2022-09-28 12:19
Looks like this was done in c7c8770a4610a318e9a7ad9bd504ce3dea6f035a, and I can confirm that my system which was misbehaving successfully saw and installed the update this morning.  Thanks, @frenck!

**Comment by frenck** [comment] 2022-09-28 12:21
Oh right, yeah this indeed was adjusted this morning 👍 

I will close it on this end.

../Frenck

**Closed by frenck** 2022-09-28 12:21 UTC
